#use docker-compose -p EZ-Apply up
version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "5000:5000"
